/* Editor seed content — the ANALYSE and PRÉSENTATION halves of the source prompt, pre-converted
   to Quill Deltas (foundation plan §7.1: serialization is one-way, so nothing parses text back
   into the editor and there is no Markdown parser in the product).

   GENERATED, not hand-edited. Regenerate from the two source files in
   docs/plan-implementation/leverage-prompt-generator/ when they change; tests.html asserts that
   DeltaText.toText() of each seed reproduces its source section, so drift fails loudly.

   Generated 2026-09-17 from leverage-prompt.fr.md and leverage-prompt.en.md. */
window.LevierSeeds = {
"analysis": {
"fr": {"ops":[
  {"insert":"ANALYSE","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":1}},
  {"insert":"1. Financement","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculer pour chaque horizon :"},
  {"insert":"\n"},
  {"insert":"paiements totaux;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"capital remboursé;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"intérêts payés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"solde restant;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"coût effectif du financement;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"effort de trésorerie mensuel et annuel."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Si le taux est variable, comparer le scénario de référence avec des scénarios raisonnables de hausse et de baisse des taux."},
  {"insert":"\n"},
  {"insert":"Ne pas considérer le remboursement du capital comme une dépense économique : il réduit simultanément la dette."},
  {"insert":"\n"},
  {"insert":"2. Fiscalité","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Appliquer le traitement fiscal approprié au type de compte et à la province indiqués dans les variables."},
  {"insert":"\n"},
  {"insert":"Lorsque pertinent, considérer :"},
  {"insert":"\n"},
  {"insert":"déductibilité des intérêts;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"gains en capital;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"dividendes;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"revenus d’intérêts;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"retraits de comptes enregistrés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"pertes en capital."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Pour un compte non enregistré, distinguer les sources de rendement lorsque leur traitement fiscal influence significativement le résultat."},
  {"insert":"\n"},
  {"insert":"Indiquer explicitement les hypothèses fiscales utilisées."},
  {"insert":"\n"},
  {"insert":"3. Rendement de l’investissement","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Pour chaque rendement et chaque horizon, calculer :"},
  {"insert":"\n"},
  {"insert":"valeur brute du portefeuille;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"frais de gestion cumulés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"valeur après impôt;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"rendement annualisé;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"résultat nominal;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"résultat réel après inflation."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Ne pas considérer qu’un rendement espéré supérieur au taux d’emprunt implique automatiquement que la stratégie est avantageuse. Le rendement du portefeuille est incertain alors que le coût de la dette est contractuel."},
  {"insert":"\n"},
  {"insert":"4. Scénarios de marché","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Analyser :"},
  {"insert":"\n"},
  {"insert":"Marché normal","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Aucune correction majeure."},
  {"insert":"\n"},
  {"insert":"Krach au début","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Appliquer la correction définie dans les variables au début de l’horizon."},
  {"insert":"\n"},
  {"insert":"Krach au milieu","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Appliquer la même correction approximativement au milieu de l’horizon."},
  {"insert":"\n"},
  {"insert":"Krach vers la fin","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Appliquer la correction peu avant la fin de l’horizon."},
  {"insert":"\n"},
  {"insert":"Comparer les résultats afin d’illustrer le risque lié à la séquence des rendements."},
  {"insert":"\n"},
  {"insert":"5. Valeur nette","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculer :"},
  {"insert":"\n"},
  {"insert":"Valeur nette = valeur après impôt du portefeuille − solde restant de la dette − frais de liquidation éventuels.","attributes":{"bold":true}},
  {"insert":"\n"},
  {"insert":"Puis :"},
  {"insert":"\n"},
  {"insert":"Gain/perte économique = valeur nette − capitaux personnels nets injectés dans la stratégie.","attributes":{"bold":true}},
  {"insert":"\n"},
  {"insert":"Éviter tout double comptage du remboursement du capital."},
  {"insert":"\n"},
  {"insert":"6. Stratégies de comparaison","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Comparer trois stratégies avec un effort de trésorerie aussi équivalent que possible."},
  {"insert":"\n"},
  {"insert":"A — Investissement avec effet de levier","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Emprunter le montant indiqué et l’investir immédiatement."},
  {"insert":"\n"},
  {"insert":"B — Investissement sans effet de levier","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Ne pas emprunter et investir progressivement l’équivalent de l’effort de trésorerie nécessaire à la stratégie A."},
  {"insert":"\n"},
  {"insert":"C — Réduction de dette","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Ne pas effectuer l’investissement avec effet de levier et utiliser le même effort de trésorerie pour réduire une dette existante."},
  {"insert":"\n"},
  {"insert":"Expliquer les ajustements nécessaires pour assurer une comparaison économiquement équitable."},
  {"insert":"\n"},
  {"insert":"7. Seuil de rentabilité","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculer le rendement annuel approximatif nécessaire pour que la stratégie avec effet de levier :"},
  {"insert":"\n"},
  {"insert":"couvre son coût de financement;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"atteigne un gain économique nul après impôt et frais;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"dépasse la stratégie sans levier;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"dépasse la stratégie de remboursement de dette."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Présenter les seuils avant et après fiscalité lorsque pertinent."},
  {"insert":"\n"},
  {"insert":"8. Analyse de sensibilité","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Mesurer l’impact des principales variables :"},
  {"insert":"\n"},
  {"insert":"rendement;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"taux d’intérêt;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"inflation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"fiscalité;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"frais de gestion;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"horizon;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"ampleur du krach;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"moment du krach;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"volatilité."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Identifier les variables ayant le plus d’impact sur le résultat."},
  {"insert":"\n"},
  {"insert":"9. Simulation Monte-Carlo","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Si activée dans les variables, effectuer une simulation probabiliste."},
  {"insert":"\n"},
  {"insert":"Présenter :"},
  {"insert":"\n"},
  {"insert":"P10;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P25;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P50;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P75;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P90;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probabilité de perte nette;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probabilité de sous-performer le coût du financement;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probabilité de sous-performer la stratégie sans levier."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Expliquer les hypothèses utilisées pour le rendement moyen, la volatilité et la distribution des rendements."},
  {"insert":"\n"},
  {"insert":"10. Stress tests","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Tester des combinaisons raisonnables d’événements défavorables, notamment :"},
  {"insert":"\n"},
  {"insert":"krach boursier + hausse des taux;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"rendement faible prolongé + taux élevés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"krach + besoin de liquidation anticipée."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Évaluer l’impact sur la valeur nette et les besoins de trésorerie."},
  {"insert":"\n"}
]},
"en": {"ops":[
  {"insert":"ANALYSIS","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":1}},
  {"insert":"1. Financing","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculate for each horizon:"},
  {"insert":"\n"},
  {"insert":"total payments;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"principal repaid;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"interest paid;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"remaining balance;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"effective cost of the financing;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"monthly and annual cash-flow effort."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"If the rate is variable, compare the baseline scenario with reasonable rate-increase and rate-decrease scenarios."},
  {"insert":"\n"},
  {"insert":"Do not treat the repayment of principal as an economic expense: it simultaneously reduces the debt."},
  {"insert":"\n"},
  {"insert":"2. Taxation","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Apply the tax treatment appropriate to the account type and province indicated in the variables."},
  {"insert":"\n"},
  {"insert":"Where relevant, consider:"},
  {"insert":"\n"},
  {"insert":"deductibility of interest;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"capital gains;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"dividends;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"interest income;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"withdrawals from registered accounts;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"capital losses."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"For a non-registered account, distinguish between the sources of return when their tax treatment significantly influences the result."},
  {"insert":"\n"},
  {"insert":"Explicitly state the tax assumptions used."},
  {"insert":"\n"},
  {"insert":"3. Investment return","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"For each return and each horizon, calculate:"},
  {"insert":"\n"},
  {"insert":"gross portfolio value;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"cumulative management fees;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"after-tax value;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"annualized return;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"nominal result;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"real result after inflation."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Do not assume that an expected return higher than the borrowing rate automatically implies that the strategy is advantageous. The portfolio's return is uncertain whereas the cost of the debt is contractual."},
  {"insert":"\n"},
  {"insert":"4. Market scenarios","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Analyze:"},
  {"insert":"\n"},
  {"insert":"Normal market","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"No major correction."},
  {"insert":"\n"},
  {"insert":"Crash at the beginning","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Apply the correction defined in the variables at the beginning of the horizon."},
  {"insert":"\n"},
  {"insert":"Crash in the middle","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Apply the same correction approximately at the middle of the horizon."},
  {"insert":"\n"},
  {"insert":"Crash near the end","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Apply the correction shortly before the end of the horizon."},
  {"insert":"\n"},
  {"insert":"Compare the results in order to illustrate the risk related to the sequence of returns."},
  {"insert":"\n"},
  {"insert":"5. Net worth","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculate:"},
  {"insert":"\n"},
  {"insert":"Net worth = after-tax value of the portfolio − remaining debt balance − any liquidation fees.","attributes":{"bold":true}},
  {"insert":"\n"},
  {"insert":"Then:"},
  {"insert":"\n"},
  {"insert":"Economic gain/loss = net worth − net personal capital injected into the strategy.","attributes":{"bold":true}},
  {"insert":"\n"},
  {"insert":"Avoid any double counting of the principal repayment."},
  {"insert":"\n"},
  {"insert":"6. Comparison strategies","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Compare three strategies with a cash-flow effort that is as equivalent as possible."},
  {"insert":"\n"},
  {"insert":"A — Leveraged investment","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Borrow the stated amount and invest it immediately."},
  {"insert":"\n"},
  {"insert":"B — Unleveraged investment","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Do not borrow, and progressively invest the equivalent of the cash-flow effort required by strategy A."},
  {"insert":"\n"},
  {"insert":"C — Debt reduction","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":3}},
  {"insert":"Do not carry out the leveraged investment and use the same cash-flow effort to reduce an existing debt."},
  {"insert":"\n"},
  {"insert":"Explain the adjustments needed to ensure an economically fair comparison."},
  {"insert":"\n"},
  {"insert":"7. Break-even point","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Calculate the approximate annual return required for the leveraged strategy to:"},
  {"insert":"\n"},
  {"insert":"cover its financing cost;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"reach a zero economic gain after tax and fees;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"outperform the unleveraged strategy;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"outperform the debt-repayment strategy."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Present the thresholds before and after tax where relevant."},
  {"insert":"\n"},
  {"insert":"8. Sensitivity analysis","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Measure the impact of the main variables:"},
  {"insert":"\n"},
  {"insert":"return;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"interest rate;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"inflation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"taxation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"management fees;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"horizon;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"magnitude of the crash;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"timing of the crash;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"volatility."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Identify the variables with the greatest impact on the result."},
  {"insert":"\n"},
  {"insert":"9. Monte Carlo simulation","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"If enabled in the variables, run a probabilistic simulation."},
  {"insert":"\n"},
  {"insert":"Present:"},
  {"insert":"\n"},
  {"insert":"P10;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P25;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P50;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P75;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"P90;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probability of a net loss;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probability of underperforming the cost of the financing;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"probability of underperforming the unleveraged strategy."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Explain the assumptions used for the average return, the volatility and the distribution of returns."},
  {"insert":"\n"},
  {"insert":"10. Stress tests","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":2}},
  {"insert":"Test reasonable combinations of adverse events, in particular:"},
  {"insert":"\n"},
  {"insert":"market crash + rate increase;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"prolonged low returns + high rates;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"crash + need for early liquidation."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Assess the impact on net worth and on cash-flow needs."},
  {"insert":"\n"}
]}
},
"presentation": {
"fr": {"ops":[
  {"insert":"PRÉSENTATION DES RÉSULTATS","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":1}},
  {"insert":"Présenter les résultats principalement sous forme de tableaux comparatifs."},
  {"insert":"\n"},
  {"insert":"Pour chaque horizon, afficher au minimum :"},
  {"insert":"\n"},
  {"insert":"valeur finale du portefeuille;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"valeur après impôt;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"intérêts cumulés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"capital remboursé;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"solde restant de la dette;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"capitaux personnels injectés;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"valeur nette;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"gain/perte économique;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"rendement annualisé;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"résultat réel après inflation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"seuil de rentabilité."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Séparer clairement :"},
  {"insert":"\n"},
  {"insert":"résultats déterministes;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"scénarios de krach;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"stress tests;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"simulation probabiliste;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"comparaison des stratégies."},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"Terminer par une synthèse expliquant :"},
  {"insert":"\n"},
  {"insert":"les conditions dans lesquelles la stratégie crée ou détruit de la valeur;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"le rendement nécessaire pour justifier économiquement l’effet de levier;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"l’impact de l’horizon;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"l’impact des taux d’intérêt;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"l’impact de la fiscalité;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"l’impact de la séquence des rendements;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"les principaux risques;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"les hypothèses auxquelles les conclusions sont les plus sensibles."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Ne pas évaluer la stratégie uniquement en comparant le rendement boursier au taux d’emprunt. L’évaluer selon sa "},
  {"insert":"valeur nette, son coût d’opportunité, sa fiscalité, ses flux de trésorerie et le risque assumé","attributes":{"bold":true}},
  {"insert":"."},
  {"insert":"\n"},
  {"insert":"Signaler clairement toute donnée manquante ou approximation susceptible de modifier significativement les résultats."},
  {"insert":"\n"}
]},
"en": {"ops":[
  {"insert":"PRESENTATION OF RESULTS","attributes":{"bold":true}},
  {"insert":"\n","attributes":{"header":1}},
  {"insert":"Present the results primarily in the form of comparative tables."},
  {"insert":"\n"},
  {"insert":"For each horizon, display at a minimum:"},
  {"insert":"\n"},
  {"insert":"final portfolio value;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"after-tax value;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"cumulative interest;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"principal repaid;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"remaining debt balance;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"personal capital injected;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"net worth;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"economic gain/loss;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"annualized return;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"real result after inflation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"break-even point."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Clearly separate:"},
  {"insert":"\n"},
  {"insert":"deterministic results;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"crash scenarios;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"stress tests;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"probabilistic simulation;"},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"comparison of the strategies."},
  {"insert":"\n","attributes":{"list":"ordered"}},
  {"insert":"End with a synthesis explaining:"},
  {"insert":"\n"},
  {"insert":"the conditions under which the strategy creates or destroys value;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the return required to economically justify the leverage;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the impact of the horizon;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the impact of interest rates;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the impact of taxation;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the impact of the sequence of returns;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the main risks;"},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"the assumptions to which the conclusions are the most sensitive."},
  {"insert":"\n","attributes":{"list":"bullet"}},
  {"insert":"Do not assess the strategy solely by comparing the market return to the borrowing rate. Assess it according to its "},
  {"insert":"net worth, its opportunity cost, its taxation, its cash flows and the risk assumed","attributes":{"bold":true}},
  {"insert":"."},
  {"insert":"\n"},
  {"insert":"Clearly flag any missing data or approximation likely to significantly change the results."},
  {"insert":"\n"}
]}
}
};
